import os

from dotenv import load_dotenv

load_dotenv()

ICPDAO_APP_ENV = os.environ['ICPDAO_APP_ENV']
ICPDAO_GITHUB_APP_NAME = os.environ['ICPDAO_GITHUB_APP_NAME']
ICPDAO_GITHUB_APP_ID = os.environ['ICPDAO_GITHUB_APP_ID']
ICPDAO_GITHUB_APP_CLIENT_ID = os.environ['ICPDAO_GITHUB_APP_CLIENT_ID']
ICPDAO_GITHUB_APP_CLIENT_SECRET = os.environ['ICPDAO_GITHUB_APP_CLIENT_SECRET']

API_GATEWAY_BASE_PATH = os.environ['API_GATEWAY_BASE_PATH']
AWS_AUTHORIZER_ARN = os.environ['AWS_AUTHORIZER_ARN']

ICPDAO_MONGODB_ICPDAO_HOST = os.environ['ICPDAO_MONGODB_ICPDAO_HOST']

ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY = os.environ['ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY']
ICPDAO_ETH_DAO_ID_SALT = os.environ['ICPDAO_ETH_DAO_ID_SALT']

ICPDAO_ETH_DAOSTAKING_ADDRESS = os.environ['ICPDAO_ETH_DAOSTAKING_ADDRESS']

ICPDAO_ETH_TOKEN_FACTORY_DEPLOY_BLACK_NUMBER = 10861990

ICPDAO_MINT_TOKEN_ETH_CHAIN_ID = os.environ['ICPDAO_MINT_TOKEN_ETH_CHAIN_ID']

ICPDAO_ETH_DAO_FACTORY_OWNER_ADDRESS = os.environ['ICPDAO_ETH_DAO_FACTORY_OWNER_ADDRESS']

ICPDAO_SENTRY_DSN = os.environ['ICPDAO_SENTRY_DSN']