name: deploy

on:
  push:
    branches:
      - feature/*
      - fix/*
      - dev
      - prod

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 3.2

    - name: Start Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '3.2'
        number of databases: 10

    - name: test
      env:
        ICPDAO_APP_ENV: "TEST"
        ICPDAO_GITHUB_APP_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_ID}}
        ICPDAO_GITHUB_APP_NAME: ${{secrets.DEV__ICPDAO_GITHUB_APP_NAME}}
        ICPDAO_GITHUB_APP_CLIENT_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_ID}}
        ICPDAO_GITHUB_APP_CLIENT_SECRET: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_SECRET}}
        API_GATEWAY_BASE_PATH: ${{secrets.DEV__API_GATEWAY_BASE_PATH}}
        AWS_AUTHORIZER_ARN: ${{secrets.DEV__AWS_AUTHORIZER_ARN}}
        ICPDAO_MONGODB_ICPDAO_HOST: mongodb://127.0.0.1:27017/icpdao
        ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY: ${{secrets.DEV__ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY}}
        ICPDAO_ETH_DAO_ID_SALT: ${{secrets.DEV__ICPDAO_ETH_DAO_ID_SALT}}
        ICPDAO_ETH_DAOSTAKING_ADDRESS: "0x1111111111111111111111111111111111111111"
      run: |
        npm install
        pip install -r requirements_dev.txt
        pytest tests

  deploy_dev:
    needs: [test]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      env:
        ICPDAO_APP_ENV: "DEV"
        SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        ICPDAO_GITHUB_APP_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_ID}}
        ICPDAO_GITHUB_APP_NAME: ${{secrets.DEV__ICPDAO_GITHUB_APP_NAME}}
        ICPDAO_GITHUB_APP_CLIENT_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_ID}}
        ICPDAO_GITHUB_APP_CLIENT_SECRET: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_SECRET}}
        API_GATEWAY_BASE_PATH: ${{secrets.DEV__API_GATEWAY_BASE_PATH}}
        AWS_AUTHORIZER_ARN: ${{secrets.DEV__AWS_AUTHORIZER_ARN}}
        ICPDAO_MONGODB_ICPDAO_HOST: ${{secrets.DEV__ICPDAO_MONGODB_ICPDAO_HOST}}
        ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY: ${{secrets.DEV__ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY}}
        ICPDAO_ETH_DAO_ID_SALT: ${{secrets.DEV__ICPDAO_ETH_DAO_ID_SALT}}
        ICPDAO_ETH_DAOSTAKING_ADDRESS: ${{secrets.DEV__ICPDAO_ETH_DAOSTAKING_ADDRESS}}
      run: |
        npm install -g serverless@2.35.0
        npm install
        sls deploy --stage dev

  deploy_prod:
    needs: [test]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      env:
        ICPDAO_APP_ENV: "PROD"
        SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        ICPDAO_GITHUB_APP_ID: ${{secrets.PROD__ICPDAO_GITHUB_APP_ID}}
        ICPDAO_GITHUB_APP_NAME: ${{secrets.PROD__ICPDAO_GITHUB_APP_NAME}}
        ICPDAO_GITHUB_APP_CLIENT_ID: ${{secrets.PROD__ICPDAO_GITHUB_APP_CLIENT_ID}}
        ICPDAO_GITHUB_APP_CLIENT_SECRET: ${{secrets.PROD__ICPDAO_GITHUB_APP_CLIENT_SECRET}}
        API_GATEWAY_BASE_PATH: ${{secrets.PROD__API_GATEWAY_BASE_PATH}}
        AWS_AUTHORIZER_ARN: ${{secrets.PROD__AWS_AUTHORIZER_ARN}}
        ICPDAO_MONGODB_ICPDAO_HOST: ${{secrets.PROD__ICPDAO_MONGODB_ICPDAO_HOST}}
        ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY: ${{secrets.PROD__ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY}}
        ICPDAO_ETH_DAO_ID_SALT: ${{secrets.PROD__ICPDAO_ETH_DAO_ID_SALT}}
        ICPDAO_ETH_DAOSTAKING_ADDRESS: ${{secrets.PROD__ICPDAO_ETH_DAOSTAKING_ADDRESS}}
      run: |
        npm install -g serverless@2.35.0
        npm install
        sls deploy --stage prod
